apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spring-graceful-shutdown
  region: ap-northeast-1
  version: '1.25'

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

fargateProfiles:
  - name: default
    selectors:
      - namespace: kube-system
      - namespace: default
      - namespace: argo-rollouts
